#!/bin/bash
# This deploy hook gets executed after dependencies are resolved and the
# build hook has been run but before the application has been started back
# up again.  This script gets executed directly, so it could be python, php,
# ruby, etc.
set -xe

source ${OPENSHIFT_HOMEDIR}app-root/runtime/dependencies/python/virtenv/bin/activate

pip install -U setuptools
pip install -Ur ${OPENSHIFT_REPO_DIR}requirements.txt

python ${OPENSHIFT_REPO_DIR}manage.py raven test
python ${OPENSHIFT_REPO_DIR}manage.py test MASAS

python ${OPENSHIFT_REPO_DIR}manage.py migrate --noinput

mkdir -p $OPENSHIFT_REPO_DIR/wsgi/static/collected

python ${OPENSHIFT_REPO_DIR}manage.py collectstatic --noinput
