#!/bin/bash
# This deploy hook gets executed after dependencies are resolved and the
# build hook has been run but before the application has been started back
# up again.  This script gets executed directly, so it could be python, php,
# ruby, etc.
set -xe

source ${OPENSHIFT_HOMEDIR}app-root/runtime/dependencies/python/virtenv/bin/activate

pip install -U setuptools
pip install -Ur ${OPENSHIFT_REPO_DIR}requirements.txt

python ${OPENSHIFT_REPO_DIR}manage.py raven test

python ${OPENSHIFT_REPO_DIR}manage.py migrate --noinput

mkdir -p $OPENSHIFT_REPO_DIR/wsgi/static/collected

python ${OPENSHIFT_REPO_DIR}manage.py collectstatic --noinput


curl -X DELETE "https://api.cloudflare.com/client/v4/zones/$CLOUDFLARE_ZONE_ID/purge_cache" \
     -H "X-Auth-Email: $CLOUDFLARE_API_EMAIL" \
     -H "X-Auth-Key: $CLOUDFLARE_API_KEY" \
     -H "Content-Type: application/json" \
     --data '{"files":["http://www.masas.fm/static/js/bundle.js"]}'
