var React = require("react")

// var {goToURL} = require("../../MASAS_functions.jsx")
// var { Link } = require("../UI/UI.jsx")

// var Template = (props) => {

// }

var Rest = React.createClass({
	propTypes: {
	},

	componentWillMount: function() {
		// this.props.updateTitle('Template', '0')		// 0 = menu icon; 1 = arrow back
	},

	render: function() {
		return (
			<div className="legals-content">
				<h3>Welcome to</h3>



					<h2>MASAS - 'Make A Sound And Share' Cookie Policy</h2>

					<p>In common with most other websites, we use cookies and similar technologies to help us understand how our users, such as yourself, use MASAS,  so that we can keep improving the platform to meet your needs and exceed your expectations. We have created this Policy to provide you with clear and explicit information about the technologies that we use on MASAS, and your choices when it comes to these technologies.</p>
					<p>MASAS collects the least amount of information possible about users such as yourself on MASAS so that we can better understand your what you like, as well as what you dislike about the platform.</p>
					<p>If you choose to use the Platform without blocking or disabling cookies or opting out of other technologies, you will indicate your consent to our use of these cookies and other technologies and to our use of any personal information that we collect using these technologies. If you do not consent to the use of these technologies, please be sure to block or disable them using your browser settings, the Opting-Out links identified in this policy, or the settings within our mobile apps.</p>
					 
					<h2>What are Cookies?</h2>

					<p>They definitely are NOT the cookies that you buy or make in your kitchen. Although we definitely recommend you to go and grab some right now. Reading is always better with some sweet treats by your side :).</p>

					<p>Cookies are small text files that are placed on your computer by websites that you visit. These text files can be read by these websites and help to identify you when you return to a website. Cookies can be 'persisten' or 'session' cookies. Persistent cookies remain on your computer when you have gone offline, while session cookies are deleted as soon as you close your web browser.</p>
					<p>To find out more about cookies, including how to see what cookies have been set and how to block and delete cookies, please visit http://www.aboutcookies.org/.</p>
					 
					<h2>MASAS Cookies</h2>

					<p>We use our own cookies to recognize you when you visit our website or use our apps. This means that you don’t have to log in each time you visit, and we can remember your preferences and settings.</p>
					 
					<h2>Third Party Cookies</h2>

					<p>In addition to our own cookies, we work with various reputable companies to help us analyze how the Platform is used, and to optimize our Website and Apps to deliver the best possible user experience to you and the other users on MASAS. The following companies help us achieve this through use of cookies:</p>

					<h3>Google Analytics and Google Website Optimizer</h3>
					 
					<p>Google Analytics and Google Website Optimizer are services provided by Google, Inc. ('Google'). Google Analytics uses cookies to help us analyze how users use our website, our mobile site and apps. Google Web Optimzer uses the same cookies to measure how different users respond to different content. The information generated by these cookies (including your shortened IP address) is transmitted to and stored by Google on servers in the United States. Google will use this information for the purpose of evaluating your, and other users’, use of the platform on both our websites and Apps, compiling reports for us on website activity and providing other services relating to website activity and Internet usage. Please note that Google only receives your shortened IP address. This is sufficient for Google to identify (approximately) the country from which you are visiting our sites or accessing our players, but is not sufficient to identify you, or your computer or mobile device, individually.</p>
					<h4>Google cookies are those beginning '__ut'.</h4>

					<p>You can find more information on the steps that Google take to Safeguard Your Data by visiting this URL (below):</p>
					<ul><li>https://support.google.com/analytics/answer/6004245</li></ul>

					<p>And you can find their Privacy Policy by going visiting this URL(below):</p>
					<ul><li>https://www.google.com/intl/en/policies/privacy/</li></ul>

					<p>To opt out of this analysis by Google, please see our Opting Out section below.</p>

					 
					 
					<h2>Opting Out</h2>

					<p>We think it's important that you are able to control the collection of personal data relating to your use of MASAS, and have therefore made sure that you can opt out of any personal data collection using cookies or other technologies as set out below. (Please note that you cannot opt out of our use of Flash cookies or HTML5 local storage as these are necessary for the technical operation of the platform. However, we do not use these technologies to collect any personal data.)</p>

					<h3>Cookies:</h3>
					<p>You can use the settings within your browser to control the cookies that are set on your computer or mobile device. However, please be aware that cookies are very important to many aspects for the Platform - if you set your browser to reject cookies, you may not be able to enjoy all of the features of the Platform. To find out how to see what cookies have been set and how to reject and delete cookies, please visit: </p>
					<ul>
						<li>
							<a target="_blank" href="http://www.aboutcookies.org">http://www.aboutcookies.org.</a>
						</li>
					</ul>

					<p>To opt-out of analysis by Google Analytics on our website and other websites, please visit:</p>
					<ul>
						<li>
							<a target="_blank" href="http://tools.google.com/dlpage/gaoptout">http://tools.google.com/dlpage/gaoptout</a>.
						</li>
					</ul>

					<p>To opt-out of location tracking when using our apps, you can use the settings of your device to give or refuse permission of your current location to certain apps.</p>
					 
					<h2>Consent to Cookies and Similar Technologies</h2>

					<p>We have done our best to provide you with clear and comprehensive information about our use of cookies and similar technologies. If you choose to use our Platform without blocking or disabling cookies or opting out of these technologies (as described above), you will indicate your consent to our use of these cookies and other technologies and to our use (in accordance with this policy and our Privacy Policy) of any personal information that we collect using these technologies. If you do not consent to the use of these technologies, please be sure to block or disable them using your browser settings, the opt-out links above, or on the settings on your mobile device.</p>
					 
					<p>Last Amended: 07 September 2016</p>
 

			</div>
		)
	}
})

module.exports = Rest