# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-12 10:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateUploaded', models.DateTimeField(auto_now_add=True)),
                ('trackTitle', models.CharField(blank=True, default='', max_length=100)),
                ('trackDuration', models.IntegerField()),
                ('SC_ID', models.IntegerField()),
                ('trackArtist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='songs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dislikes', models.ManyToManyField(blank=True, null=True, related_name='dislikedBy', to='MASAS.Song')),
                ('likes', models.ManyToManyField(blank=True, null=True, related_name='likedBy', to='MASAS.Song')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userProfile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
