# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-13 16:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('MASAS', '0003_add_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 3, 13, 16, 42, 0, 96878, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
