# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-13 17:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MASAS', '0005_sc_id_unique'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='like',
            unique_together=set([('user', 'song')]),
        ),
    ]
