# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-14 00:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


def delete_songs(apps, schema_editor):
    Song = apps.get_model('MASAS.Song')
    Song.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('MASAS', '0007_add_play'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeInterval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.PositiveIntegerField()),
                ('end', models.PositiveIntegerField()),
            ],
        ),
        migrations.RunPython(delete_songs),
        migrations.AddField(
            model_name='song',
            name='timeInterval',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='MASAS.TimeInterval'),
            preserve_default=False,
        ),
    ]
