# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-15 00:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MASAS', '0010_link_rewrite'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('status', models.SmallIntegerField(choices=[(-3, 'Report SPAM'), (-2, 'Report Copyright infrigement'), (-1, 'Dislike'), (1, 'Status'), (2, 'Love'), (5, 'Life changing')], default=1)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MASAS.Song')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='like',
            name='song',
        ),
        migrations.RemoveField(
            model_name='like',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='user',
            name='likes',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
        migrations.AddField(
            model_name='status',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='status',
            unique_together=set([('user', 'song')]),
        ),
    ]
