# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-06 11:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MASAS', '0011_link_rewrite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='status',
            field=models.SmallIntegerField(choices=[(-3, 'Report SPAM'), (-2, 'Report Copyright infrigement'), (-1, 'Dislike'), (1, 'Like'), (2, 'Love'), (5, 'Life changing')], default=1),
        ),
    ]
