# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-06 14:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MASAS', '0011_link_rewrite'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.PositiveIntegerField(choices=[('Accepted terms and conditions', 1)])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='status',
            name='status',
            field=models.SmallIntegerField(choices=[(-3, 'Report SPAM'), (-2, 'Report Copyright infrigement'), (-1, 'Dislike'), (1, 'Like'), (2, 'Love'), (5, 'Life changing')], default=1),
        ),
    ]
