# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-06 13:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MASAS', '0012_auto_20160406_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='accepted_terms',
            field=models.BooleanField(default=False),
        ),
    ]
