# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-06 14:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MASAS', '0012_add_userstep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstep',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usersteps', to=settings.AUTH_USER_MODEL),
        ),
    ]
