# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-10 09:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MASAS', '0013_add_userstep'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='deleted',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
