# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-09 09:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MASAS', '0015_default_user_active_to_false'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstep',
            name='step',
            field=models.PositiveIntegerField(choices=[(1, 'Accepted terms and conditions'), (2, 'Can log in')]),
        ),
    ]
