# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-15 02:13
from __future__ import unicode_literals

from django.db import migrations, models


def update_play_count(apps, schema_editor):
    Song = apps.get_model('MASAS', 'Song')

    for song in Song.objects.filter(deleted=None):
        song.play_count = song.play_set.count()
        song.save()


class Migration(migrations.Migration):

    dependencies = [
        ('MASAS', '0017_is_active_true_default_again'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='play_count',
            field=models.IntegerField(db_index=True, default=0),
            preserve_default=False,
        ),
        migrations.RunPython(
            update_play_count
        ),
    ]
